# Generated by Django 5.0.6 on 2024-07-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0014_alter_booking_id_alter_category_id_alter_checkin_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='price_per_night',
            new_name='price',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
